"""add calendar production assets and proof

Revision ID: 2378e805851a
Revises: db0eecfedeeb
Create Date: 2026-07-23 16:41:05.431735
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2378e805851a"
down_revision: str | None = "db0eecfedeeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capacity_plans",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("available_hours", sa.Float(), nullable=False),
        sa.Column("max_shoots", sa.Integer(), nullable=False),
        sa.Column("max_edits", sa.Integer(), nullable=False),
        sa.Column("fallback_plan", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_capacity_plans_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity_plans")),
        sa.UniqueConstraint("brand_id", "week_start", name=op.f("uq_capacity_plans_brand_id")),
    )
    op.create_index(
        op.f("ix_capacity_plans_brand_id"), "capacity_plans", ["brand_id"], unique=False
    )
    op.create_index(op.f("ix_capacity_plans_is_demo"), "capacity_plans", ["is_demo"], unique=False)
    op.create_index(
        op.f("ix_capacity_plans_week_start"), "capacity_plans", ["week_start"], unique=False
    )
    op.create_table(
        "calendar_events",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("capacity_units", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_calendar_events_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_calendar_events_content_item_id_content_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_events")),
    )
    op.create_index(
        op.f("ix_calendar_events_brand_id"), "calendar_events", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_content_item_id"),
        "calendar_events",
        ["content_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_events_event_type"), "calendar_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_is_demo"), "calendar_events", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_start_at"), "calendar_events", ["start_at"], unique=False
    )
    op.create_index(op.f("ix_calendar_events_status"), "calendar_events", ["status"], unique=False)
    op.create_table(
        "proof_items",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("proof_type", sa.String(length=80), nullable=False),
        sa.Column("credibility_gap", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("constraints", sa.Text(), nullable=False),
        sa.Column("process", sa.Text(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("lessons", sa.Text(), nullable=False),
        sa.Column("evidence_links", sa.JSON(), nullable=False),
        sa.Column("asset_ids", sa.JSON(), nullable=False),
        sa.Column("permission_status", sa.String(length=60), nullable=False),
        sa.Column("sensitivity", sa.String(length=60), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "EVIDENCE_NEEDED",
                "VERIFIED",
                "APPROVED",
                "ARCHIVED",
                name="proofstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_proof_items_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_proof_items_content_item_id_content_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proof_items")),
    )
    op.create_index(op.f("ix_proof_items_brand_id"), "proof_items", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_proof_items_content_item_id"), "proof_items", ["content_item_id"], unique=False
    )
    op.create_index(op.f("ix_proof_items_is_demo"), "proof_items", ["is_demo"], unique=False)
    op.create_index(
        op.f("ix_proof_items_permission_status"), "proof_items", ["permission_status"], unique=False
    )
    op.create_index(op.f("ix_proof_items_proof_type"), "proof_items", ["proof_type"], unique=False)
    op.create_index(op.f("ix_proof_items_status"), "proof_items", ["status"], unique=False)
    op.create_table(
        "production_plans",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("script_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("creative_treatment", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=240), nullable=True),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("wardrobe", sa.JSON(), nullable=False),
        sa.Column("props", sa.JSON(), nullable=False),
        sa.Column("lighting_plan", sa.Text(), nullable=False),
        sa.Column("music_direction", sa.Text(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "BLOCKED",
                "READY",
                "IN_PROGRESS",
                "COMPLETE",
                name="productionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("readiness_score", sa.Float(), nullable=False),
        sa.Column("blockers", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_production_plans_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_production_plans_content_item_id_content_items"),
        ),
        sa.ForeignKeyConstraint(
            ["script_id"], ["scripts.id"], name=op.f("fk_production_plans_script_id_scripts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_plans")),
    )
    op.create_index(
        op.f("ix_production_plans_brand_id"), "production_plans", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_plans_content_item_id"),
        "production_plans",
        ["content_item_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_production_plans_is_demo"), "production_plans", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_production_plans_scheduled_at"), "production_plans", ["scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_production_plans_script_id"), "production_plans", ["script_id"], unique=True
    )
    op.create_index(
        op.f("ix_production_plans_status"), "production_plans", ["status"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("production_plan_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("filename", sa.String(length=240), nullable=False),
        sa.Column("storage_key", sa.String(length=800), nullable=False),
        sa.Column("media_type", sa.String(length=60), nullable=False),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("people", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=240), nullable=True),
        sa.Column("orientation", sa.String(length=40), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column(
            "rights_status",
            sa.Enum(
                "UNKNOWN", "OWNED", "LICENSED", "RESTRICTED", name="rightsstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("rights_notes", sa.Text(), nullable=True),
        sa.Column("original_preserved", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_assets_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_assets_content_item_id_content_items"),
        ),
        sa.ForeignKeyConstraint(
            ["production_plan_id"],
            ["production_plans.id"],
            name=op.f("fk_assets_production_plan_id_production_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_index(op.f("ix_assets_brand_id"), "assets", ["brand_id"], unique=False)
    op.create_index(op.f("ix_assets_checksum_sha256"), "assets", ["checksum_sha256"], unique=False)
    op.create_index(op.f("ix_assets_content_item_id"), "assets", ["content_item_id"], unique=False)
    op.create_index(op.f("ix_assets_is_demo"), "assets", ["is_demo"], unique=False)
    op.create_index(op.f("ix_assets_media_type"), "assets", ["media_type"], unique=False)
    op.create_index(
        op.f("ix_assets_production_plan_id"), "assets", ["production_plan_id"], unique=False
    )
    op.create_index(op.f("ix_assets_rights_status"), "assets", ["rights_status"], unique=False)
    op.create_table(
        "production_checklist_items",
        sa.Column("production_plan_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("phase", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["production_plan_id"],
            ["production_plans.id"],
            name=op.f("fk_production_checklist_items_production_plan_id_production_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_checklist_items")),
    )
    op.create_index(
        op.f("ix_production_checklist_items_is_complete"),
        "production_checklist_items",
        ["is_complete"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_checklist_items_phase"),
        "production_checklist_items",
        ["phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_checklist_items_production_plan_id"),
        "production_checklist_items",
        ["production_plan_id"],
        unique=False,
    )
    op.create_table(
        "production_scenes",
        sa.Column("production_plan_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("purpose", sa.String(length=500), nullable=False),
        sa.Column("dialogue", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["production_plan_id"],
            ["production_plans.id"],
            name=op.f("fk_production_scenes_production_plan_id_production_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_scenes")),
        sa.UniqueConstraint(
            "production_plan_id", "sequence", name=op.f("uq_production_scenes_production_plan_id")
        ),
    )
    op.create_index(
        op.f("ix_production_scenes_production_plan_id"),
        "production_scenes",
        ["production_plan_id"],
        unique=False,
    )
    op.create_table(
        "production_shots",
        sa.Column("production_scene_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("framing", sa.String(length=120), nullable=False),
        sa.Column("camera_angle", sa.String(length=120), nullable=False),
        sa.Column("movement", sa.String(length=120), nullable=False),
        sa.Column("lighting", sa.String(length=240), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("is_b_roll", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["production_scene_id"],
            ["production_scenes.id"],
            name=op.f("fk_production_shots_production_scene_id_production_scenes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_shots")),
        sa.UniqueConstraint(
            "production_scene_id", "sequence", name=op.f("uq_production_shots_production_scene_id")
        ),
    )
    op.create_index(
        op.f("ix_production_shots_production_scene_id"),
        "production_shots",
        ["production_scene_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_shots_status"), "production_shots", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_shots_status"), table_name="production_shots")
    op.drop_index(op.f("ix_production_shots_production_scene_id"), table_name="production_shots")
    op.drop_table("production_shots")
    op.drop_index(op.f("ix_production_scenes_production_plan_id"), table_name="production_scenes")
    op.drop_table("production_scenes")
    op.drop_index(
        op.f("ix_production_checklist_items_production_plan_id"),
        table_name="production_checklist_items",
    )
    op.drop_index(
        op.f("ix_production_checklist_items_phase"), table_name="production_checklist_items"
    )
    op.drop_index(
        op.f("ix_production_checklist_items_is_complete"), table_name="production_checklist_items"
    )
    op.drop_table("production_checklist_items")
    op.drop_index(op.f("ix_assets_rights_status"), table_name="assets")
    op.drop_index(op.f("ix_assets_production_plan_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_media_type"), table_name="assets")
    op.drop_index(op.f("ix_assets_is_demo"), table_name="assets")
    op.drop_index(op.f("ix_assets_content_item_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_checksum_sha256"), table_name="assets")
    op.drop_index(op.f("ix_assets_brand_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_production_plans_status"), table_name="production_plans")
    op.drop_index(op.f("ix_production_plans_script_id"), table_name="production_plans")
    op.drop_index(op.f("ix_production_plans_scheduled_at"), table_name="production_plans")
    op.drop_index(op.f("ix_production_plans_is_demo"), table_name="production_plans")
    op.drop_index(op.f("ix_production_plans_content_item_id"), table_name="production_plans")
    op.drop_index(op.f("ix_production_plans_brand_id"), table_name="production_plans")
    op.drop_table("production_plans")
    op.drop_index(op.f("ix_proof_items_status"), table_name="proof_items")
    op.drop_index(op.f("ix_proof_items_proof_type"), table_name="proof_items")
    op.drop_index(op.f("ix_proof_items_permission_status"), table_name="proof_items")
    op.drop_index(op.f("ix_proof_items_is_demo"), table_name="proof_items")
    op.drop_index(op.f("ix_proof_items_content_item_id"), table_name="proof_items")
    op.drop_index(op.f("ix_proof_items_brand_id"), table_name="proof_items")
    op.drop_table("proof_items")
    op.drop_index(op.f("ix_calendar_events_status"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_start_at"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_is_demo"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_event_type"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_content_item_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_brand_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_capacity_plans_week_start"), table_name="capacity_plans")
    op.drop_index(op.f("ix_capacity_plans_is_demo"), table_name="capacity_plans")
    op.drop_index(op.f("ix_capacity_plans_brand_id"), table_name="capacity_plans")
    op.drop_table("capacity_plans")
    # ### end Alembic commands ###
