"""add memory intelligence telegram and analytics

Revision ID: 4ca6a901f2f5
Revises: 2378e805851a
Create Date: 2026-07-23 17:02:51.687982
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4ca6a901f2f5"
down_revision: str | None = "2378e805851a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("username", sa.String(length=180), nullable=False),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("url", sa.String(length=800), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("why_tracked", sa.Text(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("content_pillars", sa.JSON(), nullable=False),
        sa.Column("formats", sa.JSON(), nullable=False),
        sa.Column("voice", sa.Text(), nullable=False),
        sa.Column("hook_style", sa.Text(), nullable=False),
        sa.Column("production_style", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=240), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watch_status", sa.String(length=40), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_creators_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creators")),
        sa.UniqueConstraint("brand_id", "platform", "username", name=op.f("uq_creators_brand_id")),
    )
    op.create_index(op.f("ix_creators_brand_id"), "creators", ["brand_id"], unique=False)
    op.create_index(op.f("ix_creators_is_demo"), "creators", ["is_demo"], unique=False)
    op.create_index(op.f("ix_creators_platform"), "creators", ["platform"], unique=False)
    op.create_index(op.f("ix_creators_tier"), "creators", ["tier"], unique=False)
    op.create_index(op.f("ix_creators_watch_status"), "creators", ["watch_status"], unique=False)
    op.create_table(
        "experiments",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("variable", sa.String(length=240), nullable=False),
        sa.Column("control_conditions", sa.JSON(), nullable=False),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("expected_outcome", sa.Text(), nullable=False),
        sa.Column("success_metric", sa.String(length=240), nullable=False),
        sa.Column("measurement_start", sa.Date(), nullable=True),
        sa.Column("measurement_end", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("interpretation", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("decision", sa.String(length=120), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_experiments_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
    )
    op.create_index(op.f("ix_experiments_brand_id"), "experiments", ["brand_id"], unique=False)
    op.create_index(op.f("ix_experiments_is_demo"), "experiments", ["is_demo"], unique=False)
    op.create_index(op.f("ix_experiments_platform"), "experiments", ["platform"], unique=False)
    op.create_index(op.f("ix_experiments_status"), "experiments", ["status"], unique=False)
    op.create_table(
        "heartbeat_settings",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_hour", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("max_sources", sa.Integer(), nullable=False),
        sa.Column("max_creators", sa.Integer(), nullable=False),
        sa.Column("telegram_summary_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_heartbeat_settings_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_heartbeat_settings")),
    )
    op.create_index(
        op.f("ix_heartbeat_settings_brand_id"), "heartbeat_settings", ["brand_id"], unique=True
    )
    op.create_table(
        "memory_records",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("memory_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "canonical_status",
            sa.Enum(
                "CANONICAL",
                "WORKING",
                "ARCHIVED",
                "RESTRICTED",
                name="canonicalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("vault_path", sa.String(length=800), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.Column("sensitivity", sa.String(length=60), nullable=False),
        sa.Column("review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=60), nullable=False),
        sa.Column("embedding_status", sa.String(length=60), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_memory_records_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_records")),
        sa.UniqueConstraint("brand_id", "vault_path", name=op.f("uq_memory_records_brand_id")),
    )
    op.create_index(
        op.f("ix_memory_records_brand_id"), "memory_records", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_records_canonical_status"),
        "memory_records",
        ["canonical_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_records_content_checksum"),
        "memory_records",
        ["content_checksum"],
        unique=False,
    )
    op.create_index(op.f("ix_memory_records_is_demo"), "memory_records", ["is_demo"], unique=False)
    op.create_index(
        op.f("ix_memory_records_memory_type"), "memory_records", ["memory_type"], unique=False
    )
    op.create_index(
        op.f("ix_memory_records_sensitivity"), "memory_records", ["sensitivity"], unique=False
    )
    op.create_index(
        op.f("ix_memory_records_sync_status"), "memory_records", ["sync_status"], unique=False
    )
    op.create_table(
        "sync_events",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("direction", sa.String(length=40), nullable=False),
        sa.Column("record_type", sa.String(length=80), nullable=False),
        sa.Column("record_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("vault_path", sa.String(length=800), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("database_checksum", sa.String(length=64), nullable=True),
        sa.Column("vault_checksum", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_sync_events_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_events")),
    )
    op.create_index(op.f("ix_sync_events_brand_id"), "sync_events", ["brand_id"], unique=False)
    op.create_index(op.f("ix_sync_events_direction"), "sync_events", ["direction"], unique=False)
    op.create_index(op.f("ix_sync_events_record_id"), "sync_events", ["record_id"], unique=False)
    op.create_index(op.f("ix_sync_events_status"), "sync_events", ["status"], unique=False)
    op.create_index(op.f("ix_sync_events_vault_path"), "sync_events", ["vault_path"], unique=False)
    op.create_table(
        "telegram_messages",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("update_id", sa.String(length=120), nullable=False),
        sa.Column("sender_id", sa.String(length=120), nullable=False),
        sa.Column("message_id", sa.String(length=120), nullable=True),
        sa.Column("message_type", sa.String(length=60), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("source_reference", sa.String(length=800), nullable=True),
        sa.Column("classification", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("created_record_type", sa.String(length=80), nullable=True),
        sa.Column("created_record_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_telegram_messages_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_messages")),
        sa.UniqueConstraint("update_id", name=op.f("uq_telegram_messages_update_id")),
    )
    op.create_index(
        op.f("ix_telegram_messages_brand_id"), "telegram_messages", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_telegram_messages_is_demo"), "telegram_messages", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_telegram_messages_message_type"),
        "telegram_messages",
        ["message_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_messages_sender_id"), "telegram_messages", ["sender_id"], unique=False
    )
    op.create_index(
        op.f("ix_telegram_messages_status"), "telegram_messages", ["status"], unique=False
    )
    op.create_table(
        "benchmark_contents",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("creator_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("source_url", sa.String(length=1200), nullable=False),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("transcript_excerpt", sa.Text(), nullable=True),
        sa.Column("hook_analysis", sa.Text(), nullable=False),
        sa.Column("structure_analysis", sa.Text(), nullable=False),
        sa.Column("visual_analysis", sa.Text(), nullable=False),
        sa.Column("editing_analysis", sa.Text(), nullable=False),
        sa.Column("transferable_mechanics", sa.JSON(), nullable=False),
        sa.Column("protected_identity", sa.JSON(), nullable=False),
        sa.Column("mezie_adaptations", sa.JSON(), nullable=False),
        sa.Column("pattern_tags", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("evidence_level", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_benchmark_contents_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["creators.id"], name=op.f("fk_benchmark_contents_creator_id_creators")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_contents")),
        sa.UniqueConstraint("brand_id", "source_url", name=op.f("uq_benchmark_contents_brand_id")),
    )
    op.create_index(
        op.f("ix_benchmark_contents_brand_id"), "benchmark_contents", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_benchmark_contents_creator_id"), "benchmark_contents", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_benchmark_contents_evidence_level"),
        "benchmark_contents",
        ["evidence_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_benchmark_contents_is_demo"), "benchmark_contents", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_benchmark_contents_platform"), "benchmark_contents", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_benchmark_contents_status"), "benchmark_contents", ["status"], unique=False
    )
    op.create_table(
        "heartbeat_runs",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("source_coverage", sa.JSON(), nullable=False),
        sa.Column("model_alias", sa.String(length=120), nullable=False),
        sa.Column("tools_used", sa.JSON(), nullable=False),
        sa.Column("model_cost", sa.Float(), nullable=False),
        sa.Column("tool_cost", sa.Float(), nullable=False),
        sa.Column("context_pack_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("records_changed", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_heartbeat_runs_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["context_pack_id"],
            ["context_packs.id"],
            name=op.f("fk_heartbeat_runs_context_pack_id_context_packs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_heartbeat_runs")),
        sa.UniqueConstraint("brand_id", "run_date", name=op.f("uq_heartbeat_runs_brand_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_heartbeat_runs_idempotency_key")),
    )
    op.create_index(
        op.f("ix_heartbeat_runs_brand_id"), "heartbeat_runs", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_heartbeat_runs_context_pack_id"),
        "heartbeat_runs",
        ["context_pack_id"],
        unique=False,
    )
    op.create_index(op.f("ix_heartbeat_runs_is_demo"), "heartbeat_runs", ["is_demo"], unique=False)
    op.create_index(
        op.f("ix_heartbeat_runs_run_date"), "heartbeat_runs", ["run_date"], unique=False
    )
    op.create_index(op.f("ix_heartbeat_runs_status"), "heartbeat_runs", ["status"], unique=False)
    op.create_table(
        "daily_briefs",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("heartbeat_run_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("brief_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("what_changed", sa.JSON(), nullable=False),
        sa.Column("creator_watch", sa.JSON(), nullable=False),
        sa.Column("trend_signals", sa.JSON(), nullable=False),
        sa.Column("content_opportunities", sa.JSON(), nullable=False),
        sa.Column("risks_noise", sa.JSON(), nullable=False),
        sa.Column("recommended_actions", sa.JSON(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("coverage_gaps", sa.JSON(), nullable=False),
        sa.Column("vault_path", sa.String(length=800), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_daily_briefs_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["heartbeat_run_id"],
            ["heartbeat_runs.id"],
            name=op.f("fk_daily_briefs_heartbeat_run_id_heartbeat_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_briefs")),
        sa.UniqueConstraint("brand_id", "brief_date", name=op.f("uq_daily_briefs_brand_id")),
    )
    op.create_index(op.f("ix_daily_briefs_brand_id"), "daily_briefs", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_daily_briefs_brief_date"), "daily_briefs", ["brief_date"], unique=False
    )
    op.create_index(
        op.f("ix_daily_briefs_heartbeat_run_id"), "daily_briefs", ["heartbeat_run_id"], unique=True
    )
    op.create_index(op.f("ix_daily_briefs_is_demo"), "daily_briefs", ["is_demo"], unique=False)
    op.create_table(
        "insights",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("classification", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_insights_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_insights_content_item_id_content_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
    )
    op.create_index(op.f("ix_insights_brand_id"), "insights", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_insights_classification"), "insights", ["classification"], unique=False
    )
    op.create_index(
        op.f("ix_insights_content_item_id"), "insights", ["content_item_id"], unique=False
    )
    op.create_index(op.f("ix_insights_is_demo"), "insights", ["is_demo"], unique=False)
    op.create_index(op.f("ix_insights_status"), "insights", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_insights_status"), table_name="insights")
    op.drop_index(op.f("ix_insights_is_demo"), table_name="insights")
    op.drop_index(op.f("ix_insights_content_item_id"), table_name="insights")
    op.drop_index(op.f("ix_insights_classification"), table_name="insights")
    op.drop_index(op.f("ix_insights_brand_id"), table_name="insights")
    op.drop_table("insights")
    op.drop_index(op.f("ix_daily_briefs_is_demo"), table_name="daily_briefs")
    op.drop_index(op.f("ix_daily_briefs_heartbeat_run_id"), table_name="daily_briefs")
    op.drop_index(op.f("ix_daily_briefs_brief_date"), table_name="daily_briefs")
    op.drop_index(op.f("ix_daily_briefs_brand_id"), table_name="daily_briefs")
    op.drop_table("daily_briefs")
    op.drop_index(op.f("ix_heartbeat_runs_status"), table_name="heartbeat_runs")
    op.drop_index(op.f("ix_heartbeat_runs_run_date"), table_name="heartbeat_runs")
    op.drop_index(op.f("ix_heartbeat_runs_is_demo"), table_name="heartbeat_runs")
    op.drop_index(op.f("ix_heartbeat_runs_context_pack_id"), table_name="heartbeat_runs")
    op.drop_index(op.f("ix_heartbeat_runs_brand_id"), table_name="heartbeat_runs")
    op.drop_table("heartbeat_runs")
    op.drop_index(op.f("ix_benchmark_contents_status"), table_name="benchmark_contents")
    op.drop_index(op.f("ix_benchmark_contents_platform"), table_name="benchmark_contents")
    op.drop_index(op.f("ix_benchmark_contents_is_demo"), table_name="benchmark_contents")
    op.drop_index(op.f("ix_benchmark_contents_evidence_level"), table_name="benchmark_contents")
    op.drop_index(op.f("ix_benchmark_contents_creator_id"), table_name="benchmark_contents")
    op.drop_index(op.f("ix_benchmark_contents_brand_id"), table_name="benchmark_contents")
    op.drop_table("benchmark_contents")
    op.drop_index(op.f("ix_telegram_messages_status"), table_name="telegram_messages")
    op.drop_index(op.f("ix_telegram_messages_sender_id"), table_name="telegram_messages")
    op.drop_index(op.f("ix_telegram_messages_message_type"), table_name="telegram_messages")
    op.drop_index(op.f("ix_telegram_messages_is_demo"), table_name="telegram_messages")
    op.drop_index(op.f("ix_telegram_messages_brand_id"), table_name="telegram_messages")
    op.drop_table("telegram_messages")
    op.drop_index(op.f("ix_sync_events_vault_path"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_status"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_record_id"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_direction"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_brand_id"), table_name="sync_events")
    op.drop_table("sync_events")
    op.drop_index(op.f("ix_memory_records_sync_status"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_sensitivity"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_memory_type"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_is_demo"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_content_checksum"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_canonical_status"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_brand_id"), table_name="memory_records")
    op.drop_table("memory_records")
    op.drop_index(op.f("ix_heartbeat_settings_brand_id"), table_name="heartbeat_settings")
    op.drop_table("heartbeat_settings")
    op.drop_index(op.f("ix_experiments_status"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_platform"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_is_demo"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_brand_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_creators_watch_status"), table_name="creators")
    op.drop_index(op.f("ix_creators_tier"), table_name="creators")
    op.drop_index(op.f("ix_creators_platform"), table_name="creators")
    op.drop_index(op.f("ix_creators_is_demo"), table_name="creators")
    op.drop_index(op.f("ix_creators_brand_id"), table_name="creators")
    op.drop_table("creators")
    # ### end Alembic commands ###
