"""initial operational schema

Revision ID: c06caa04f0c9
Revises:
Create Date: 2026-07-23 15:25:03.677711
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c06caa04f0c9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("founder_name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("positioning", sa.Text(), nullable=False),
        sa.Column("signature_line", sa.String(length=240), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("name", name=op.f("uq_brands_name")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("channel", sa.String(length=40), nullable=False),
        sa.Column("intent", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("model_alias", sa.String(length=100), nullable=False),
        sa.Column("skills_used", sa.JSON(), nullable=False),
        sa.Column("tools_used", sa.JSON(), nullable=False),
        sa.Column("context_loaded", sa.JSON(), nullable=False),
        sa.Column("model_cost", sa.Float(), nullable=False),
        sa.Column("tool_cost", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_agent_runs_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_brand_id"), "agent_runs", ["brand_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("requested_by", sa.String(length=120), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("cost_estimate", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                name="approvalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=120), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_approvals_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_action_type"), "approvals", ["action_type"], unique=False)
    op.create_index(op.f("ix_approvals_brand_id"), "approvals", ["brand_id"], unique=False)
    op.create_index(op.f("ix_approvals_risk_level"), "approvals", ["risk_level"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_index(op.f("ix_approvals_target_id"), "approvals", ["target_id"], unique=False)
    op.create_index(op.f("ix_approvals_target_type"), "approvals", ["target_type"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_audit_events_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_brand_id"), "audit_events", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_table(
        "brand_documents",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("document_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("slug", sa.String(length=240), nullable=False),
        sa.Column(
            "canonical_status",
            sa.Enum(
                "CANONICAL",
                "WORKING",
                "ARCHIVED",
                "RESTRICTED",
                name="canonicalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_version_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("source_path", sa.String(length=800), nullable=True),
        sa.Column("vault_path", sa.String(length=800), nullable=True),
        sa.Column("sensitivity", sa.String(length=40), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("version_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_brand_documents_brand_id_brands")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_documents")),
        sa.UniqueConstraint("brand_id", "slug", name=op.f("uq_brand_documents_brand_id")),
    )
    op.create_index(
        op.f("ix_brand_documents_brand_id"), "brand_documents", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_brand_documents_canonical_status"),
        "brand_documents",
        ["canonical_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_brand_documents_document_type"), "brand_documents", ["document_type"], unique=False
    )
    op.create_table(
        "ideas",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_reference", sa.String(length=800), nullable=True),
        sa.Column("pillar", sa.String(length=80), nullable=True),
        sa.Column("series", sa.String(length=120), nullable=True),
        sa.Column("audience", sa.String(length=160), nullable=False),
        sa.Column("platform_fit", sa.JSON(), nullable=False),
        sa.Column("strategic_objective", sa.String(length=240), nullable=True),
        sa.Column("urgency", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CAPTURED",
                "CLARIFYING",
                "RESEARCHING",
                "SELECTED",
                "CONVERTED_TO_BRIEF",
                "ARCHIVED",
                "REJECTED",
                name="ideastatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("brand_fit_score", sa.Float(), nullable=False),
        sa.Column("audience_value_score", sa.Float(), nullable=False),
        sa.Column("proof_score", sa.Float(), nullable=False),
        sa.Column("timeliness_score", sa.Float(), nullable=False),
        sa.Column("originality_score", sa.Float(), nullable=False),
        sa.Column("feasibility_score", sa.Float(), nullable=False),
        sa.Column("strategic_importance_score", sa.Float(), nullable=False),
        sa.Column("total_priority_score", sa.Float(), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], name=op.f("fk_ideas_brand_id_brands")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ideas")),
    )
    op.create_index(op.f("ix_ideas_brand_id"), "ideas", ["brand_id"], unique=False)
    op.create_index(
        "ix_ideas_brand_status_score",
        "ideas",
        ["brand_id", "status", "total_priority_score"],
        unique=False,
    )
    op.create_index(op.f("ix_ideas_is_demo"), "ideas", ["is_demo"], unique=False)
    op.create_index(op.f("ix_ideas_pillar"), "ideas", ["pillar"], unique=False)
    op.create_index(op.f("ix_ideas_series"), "ideas", ["series"], unique=False)
    op.create_index(op.f("ix_ideas_source_type"), "ideas", ["source_type"], unique=False)
    op.create_index(op.f("ix_ideas_status"), "ideas", ["status"], unique=False)
    op.create_index(
        op.f("ix_ideas_total_priority_score"), "ideas", ["total_priority_score"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("related_type", sa.String(length=80), nullable=True),
        sa.Column("related_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], name=op.f("fk_tasks_brand_id_brands")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_brand_id"), "tasks", ["brand_id"], unique=False)
    op.create_index(op.f("ix_tasks_due_at"), "tasks", ["due_at"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "brand_document_versions",
        sa.Column("brand_document_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("approval_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_document_id"],
            ["brand_documents.id"],
            name=op.f("fk_brand_document_versions_brand_document_id_brand_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_document_versions")),
        sa.UniqueConstraint(
            "brand_document_id",
            "version_number",
            name=op.f("uq_brand_document_versions_brand_document_id"),
        ),
    )
    op.create_index(
        op.f("ix_brand_document_versions_brand_document_id"),
        "brand_document_versions",
        ["brand_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_brand_document_versions_is_active"),
        "brand_document_versions",
        ["is_active"],
        unique=False,
    )
    op.create_table(
        "content_items",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("idea_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("format", sa.String(length=80), nullable=False),
        sa.Column("pillar", sa.String(length=80), nullable=False),
        sa.Column("series", sa.String(length=120), nullable=True),
        sa.Column("audience", sa.String(length=160), nullable=False),
        sa.Column("objective", sa.String(length=240), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IDEA",
                "RESEARCH",
                "BRIEF",
                "SCRIPT",
                "REVIEW",
                "APPROVED",
                "READY_TO_SHOOT",
                "SHOT",
                "EDITING",
                "REVIEW_EDIT",
                "READY_TO_PUBLISH",
                "PUBLISHED",
                "ANALYTICS_REVIEW",
                "REPURPOSE",
                "ARCHIVED",
                name="pipelinestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publication_url", sa.String(length=800), nullable=True),
        sa.Column("readiness_score", sa.Float(), nullable=False),
        sa.Column(
            "approval_status",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                name="approvalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("blocker", sa.String(length=500), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_content_items_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["ideas.id"], name=op.f("fk_content_items_idea_id_ideas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
    )
    op.create_index(
        "ix_content_brand_status_due",
        "content_items",
        ["brand_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(op.f("ix_content_items_brand_id"), "content_items", ["brand_id"], unique=False)
    op.create_index(op.f("ix_content_items_is_demo"), "content_items", ["is_demo"], unique=False)
    op.create_index(op.f("ix_content_items_pillar"), "content_items", ["pillar"], unique=False)
    op.create_index(op.f("ix_content_items_platform"), "content_items", ["platform"], unique=False)
    op.create_index(op.f("ix_content_items_status"), "content_items", ["status"], unique=False)
    op.create_table(
        "metric_snapshots",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("engagement", sa.Integer(), nullable=False),
        sa.Column("saves", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("watch_time_seconds", sa.Float(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_metric_snapshots_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_metric_snapshots_content_item_id_content_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_snapshots")),
    )
    op.create_index(
        op.f("ix_metric_snapshots_brand_id"), "metric_snapshots", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_metric_snapshots_captured_at"), "metric_snapshots", ["captured_at"], unique=False
    )
    op.create_index(
        op.f("ix_metric_snapshots_content_item_id"),
        "metric_snapshots",
        ["content_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_snapshots_is_demo"), "metric_snapshots", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_metric_snapshots_platform"), "metric_snapshots", ["platform"], unique=False
    )
    op.create_table(
        "pipeline_events",
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("from_status", sa.String(length=40), nullable=False),
        sa.Column("to_status", sa.String(length=40), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_pipeline_events_content_item_id_content_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_events")),
    )
    op.create_index(
        op.f("ix_pipeline_events_content_item_id"),
        "pipeline_events",
        ["content_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_events_content_item_id"), table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_index(op.f("ix_metric_snapshots_platform"), table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_is_demo"), table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_content_item_id"), table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_captured_at"), table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_brand_id"), table_name="metric_snapshots")
    op.drop_table("metric_snapshots")
    op.drop_index(op.f("ix_content_items_status"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_platform"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_pillar"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_is_demo"), table_name="content_items")
    op.drop_index(op.f("ix_content_items_brand_id"), table_name="content_items")
    op.drop_index("ix_content_brand_status_due", table_name="content_items")
    op.drop_table("content_items")
    op.drop_index(
        op.f("ix_brand_document_versions_is_active"), table_name="brand_document_versions"
    )
    op.drop_index(
        op.f("ix_brand_document_versions_brand_document_id"), table_name="brand_document_versions"
    )
    op.drop_table("brand_document_versions")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_brand_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_ideas_total_priority_score"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_status"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_source_type"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_series"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_pillar"), table_name="ideas")
    op.drop_index(op.f("ix_ideas_is_demo"), table_name="ideas")
    op.drop_index("ix_ideas_brand_status_score", table_name="ideas")
    op.drop_index(op.f("ix_ideas_brand_id"), table_name="ideas")
    op.drop_table("ideas")
    op.drop_index(op.f("ix_brand_documents_document_type"), table_name="brand_documents")
    op.drop_index(op.f("ix_brand_documents_canonical_status"), table_name="brand_documents")
    op.drop_index(op.f("ix_brand_documents_brand_id"), table_name="brand_documents")
    op.drop_table("brand_documents")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_brand_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_approvals_target_type"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_target_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_risk_level"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_brand_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action_type"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_brand_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("brands")
    # ### end Alembic commands ###
