"""add brief script hook and fact check workflow

Revision ID: db0eecfedeeb
Revises: dd607cc884a2
Create Date: 2026-07-23 16:24:03.297735
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "db0eecfedeeb"
down_revision: str | None = "dd607cc884a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_briefs",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("idea_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("objective", sa.String(length=500), nullable=False),
        sa.Column("audience", sa.String(length=160), nullable=False),
        sa.Column("platform", sa.String(length=60), nullable=False),
        sa.Column("format", sa.String(length=80), nullable=False),
        sa.Column("pillar", sa.String(length=80), nullable=False),
        sa.Column("series", sa.String(length=120), nullable=True),
        sa.Column("core_message", sa.Text(), nullable=False),
        sa.Column("audience_problem", sa.Text(), nullable=False),
        sa.Column("desired_emotion", sa.String(length=120), nullable=False),
        sa.Column("desired_action", sa.String(length=240), nullable=False),
        sa.Column("proof_points", sa.JSON(), nullable=False),
        sa.Column("benchmark_references", sa.JSON(), nullable=False),
        sa.Column("visual_direction", sa.Text(), nullable=False),
        sa.Column("production_constraints", sa.JSON(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("cta", sa.String(length=500), nullable=False),
        sa.Column("success_metric", sa.String(length=240), nullable=False),
        sa.Column(
            "evidence_status",
            sa.Enum(
                "NOT_STARTED",
                "NEEDS_REVIEW",
                "VERIFIED",
                "BLOCKED",
                name="reviewstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PROOF_NEEDED", "READY", "ARCHIVED", name="briefstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_content_briefs_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_briefs_content_item_id_content_items"),
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["ideas.id"], name=op.f("fk_content_briefs_idea_id_ideas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_briefs")),
    )
    op.create_index(
        op.f("ix_content_briefs_brand_id"), "content_briefs", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_briefs_content_item_id"),
        "content_briefs",
        ["content_item_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_content_briefs_evidence_status"),
        "content_briefs",
        ["evidence_status"],
        unique=False,
    )
    op.create_index(op.f("ix_content_briefs_idea_id"), "content_briefs", ["idea_id"], unique=True)
    op.create_index(op.f("ix_content_briefs_is_demo"), "content_briefs", ["is_demo"], unique=False)
    op.create_index(op.f("ix_content_briefs_pillar"), "content_briefs", ["pillar"], unique=False)
    op.create_index(
        op.f("ix_content_briefs_platform"), "content_briefs", ["platform"], unique=False
    )
    op.create_index(op.f("ix_content_briefs_status"), "content_briefs", ["status"], unique=False)
    op.create_table(
        "scripts",
        sa.Column("brand_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_brief_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("content_item_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REVIEW",
                "APPROVED",
                "REJECTED",
                "ARCHIVED",
                name="scriptstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_version_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("version_count", sa.Integer(), nullable=False),
        sa.Column(
            "fact_check_status",
            sa.Enum(
                "NOT_STARTED",
                "NEEDS_REVIEW",
                "VERIFIED",
                "BLOCKED",
                name="reviewstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "financial_risk",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "approval_status",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                name="approvalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_scripts_brand_id_brands")
        ),
        sa.ForeignKeyConstraint(
            ["content_brief_id"],
            ["content_briefs.id"],
            name=op.f("fk_scripts_content_brief_id_content_briefs"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_scripts_content_item_id_content_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scripts")),
    )
    op.create_index(
        op.f("ix_scripts_approval_status"), "scripts", ["approval_status"], unique=False
    )
    op.create_index(op.f("ix_scripts_brand_id"), "scripts", ["brand_id"], unique=False)
    op.create_index(
        op.f("ix_scripts_content_brief_id"), "scripts", ["content_brief_id"], unique=True
    )
    op.create_index(op.f("ix_scripts_content_item_id"), "scripts", ["content_item_id"], unique=True)
    op.create_index(
        op.f("ix_scripts_fact_check_status"), "scripts", ["fact_check_status"], unique=False
    )
    op.create_index(op.f("ix_scripts_financial_risk"), "scripts", ["financial_risk"], unique=False)
    op.create_index(op.f("ix_scripts_is_demo"), "scripts", ["is_demo"], unique=False)
    op.create_index(op.f("ix_scripts_status"), "scripts", ["status"], unique=False)
    op.create_table(
        "script_versions",
        sa.Column("script_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("hook_selected", sa.Text(), nullable=False),
        sa.Column("on_screen_text", sa.JSON(), nullable=False),
        sa.Column("b_roll_notes", sa.JSON(), nullable=False),
        sa.Column("camera_notes", sa.JSON(), nullable=False),
        sa.Column("cta", sa.String(length=500), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("brand_alignment_score", sa.Float(), nullable=False),
        sa.Column("originality_score", sa.Float(), nullable=False),
        sa.Column("evidence_notes", sa.JSON(), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("approval_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_id"], ["scripts.id"], name=op.f("fk_script_versions_script_id_scripts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_script_versions")),
        sa.UniqueConstraint(
            "script_id", "version_number", name=op.f("uq_script_versions_script_id")
        ),
    )
    op.create_index(
        op.f("ix_script_versions_is_active"), "script_versions", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_script_versions_script_id"), "script_versions", ["script_id"], unique=False
    )
    op.create_table(
        "fact_checks",
        sa.Column("script_version_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "NEEDS_REVIEW",
                "VERIFIED",
                "BLOCKED",
                name="reviewstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("claim_table", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("unresolved_claims", sa.JSON(), nullable=False),
        sa.Column("verified_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("financial_classification", sa.String(length=80), nullable=False),
        sa.Column("blocked_claims", sa.JSON(), nullable=False),
        sa.Column("risk_disclosures", sa.JSON(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=120), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_version_id"],
            ["script_versions.id"],
            name=op.f("fk_fact_checks_script_version_id_script_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_checks")),
    )
    op.create_index(
        op.f("ix_fact_checks_script_version_id"), "fact_checks", ["script_version_id"], unique=True
    )
    op.create_index(op.f("ix_fact_checks_status"), "fact_checks", ["status"], unique=False)
    op.create_table(
        "hook_options",
        sa.Column("script_version_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("clarity_score", sa.Float(), nullable=False),
        sa.Column("curiosity_score", sa.Float(), nullable=False),
        sa.Column("specificity_score", sa.Float(), nullable=False),
        sa.Column("brand_fit_score", sa.Float(), nullable=False),
        sa.Column("audience_fit_score", sa.Float(), nullable=False),
        sa.Column("originality_score", sa.Float(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("is_recommended", sa.Boolean(), nullable=False),
        sa.Column("fatigue_warning", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_version_id"],
            ["script_versions.id"],
            name=op.f("fk_hook_options_script_version_id_script_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hook_options")),
    )
    op.create_index(
        op.f("ix_hook_options_script_version_id"),
        "hook_options",
        ["script_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hook_options_total_score"), "hook_options", ["total_score"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hook_options_total_score"), table_name="hook_options")
    op.drop_index(op.f("ix_hook_options_script_version_id"), table_name="hook_options")
    op.drop_table("hook_options")
    op.drop_index(op.f("ix_fact_checks_status"), table_name="fact_checks")
    op.drop_index(op.f("ix_fact_checks_script_version_id"), table_name="fact_checks")
    op.drop_table("fact_checks")
    op.drop_index(op.f("ix_script_versions_script_id"), table_name="script_versions")
    op.drop_index(op.f("ix_script_versions_is_active"), table_name="script_versions")
    op.drop_table("script_versions")
    op.drop_index(op.f("ix_scripts_status"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_is_demo"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_financial_risk"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_fact_check_status"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_content_item_id"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_content_brief_id"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_brand_id"), table_name="scripts")
    op.drop_index(op.f("ix_scripts_approval_status"), table_name="scripts")
    op.drop_table("scripts")
    op.drop_index(op.f("ix_content_briefs_status"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_platform"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_pillar"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_is_demo"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_idea_id"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_evidence_status"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_content_item_id"), table_name="content_briefs")
    op.drop_index(op.f("ix_content_briefs_brand_id"), table_name="content_briefs")
    op.drop_table("content_briefs")
    # ### end Alembic commands ###
